### ISSUE TITLE
Catch selenium.StaleElementReferenceException in waits

### ISSUE THREAD

**Issue by xsmrcek** [EmbedITCZ/jbehave-support#165]
When we continue to another page (like clicking on Submit), sometimes elements on next page aren't "ready" and throws this exception. Could we catch it and continue waiting?

**Comment by paveljandejsek** [comment]
Selenium [docs](https://www.seleniumhq.org/exceptions/stale_element_reference.jsp) say this:

> You should discard the current reference you hold and replace it, possibly by locating the element again once it is attached to the DOM.

So I guess it would not hurt to catch this exception and run the find again.

Do you have an example of something like that? What I dont know is if we should try more than once with some timeout in between (basically run the wait again) or if immediate new search is enough.

**Comment by xsmrcek** [comment]
I don't have any example we can run, just my experiances :) We solved most error with 1s static wait before accessing element. But there is one element where we need 3 sec to be 100% it's attached.

**Comment by xsmrcek** [comment]
`12:06:40.932 [pool-4-thread-1] INFO  o.j.runner.reporter.LoggingReporter - Before step: Then on [safe-notice] page wait until [errorTitle] has text Thank you!
12:06:44.040 [pool-4-thread-1] ERROR o.j.runner.reporter.LoggingReporter - Failed step: Then on [safe-notice] page wait until [errorTitle] ?has text Thank you!? cause: {}
org.openqa.selenium.StaleElementReferenceException: A node reference could not be resolved: Node with identifier 'node-9AC89D88-F1FB-4067-969C-C715AA7AAD43' was not found
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'HCI-L2736', ip: '10.130.50.57', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.1.2, javascriptEnabled: true, platform: MAC, platformName: MAC, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, setWindowRect: true, strictFileInteractability: false, webdriver.remote.sessionid: 696d995126a463d31fd34824f06..., webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}}
Session ID: 696d995126a463d31fd34824f06da130ab0dbdf6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:166)
	at org.jbehavesupport.core.internal.web.waitcondition.HasTextWebWaitCondition.lambda$evaluate$0(HasTextWebWaitCondition.java:25)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	at org.jbehavesupport.core.internal.web.waitcondition.HasTextWebWaitCondition.evaluate(HasTextWebWaitCondition.java:23)
	at org.jbehavesupport.core.web.WebSteps.waitUntilCondition(WebSteps.java:203)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:782)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:350)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1168)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1035)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:1066)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:970)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:858)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:834)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:418)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:389)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


`

**Comment by paveljandejsek** [comment]
Solved by #363 and #540
